# Generated by Django 5.1 on 2024-10-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eage',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
    ]
