# Generated by Django 5.1 on 2024-10-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_employee_eage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='eage',
        ),
    ]
